name: Lint, test and build
on: [push]
jobs:
    cache-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: npm i

    tsc-and-linting:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: npm i
            - run: npm run tsc
            - run: npm run lint

    unit-tests:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: npm i
            - run: npm run test

    build:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: npm i
            - run: npm run build
